//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SonarSweep22._01._24.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SonarSweep22._01._24.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 118
        ///121
        ///123
        ///125
        ///134
        ///132
        ///137
        ///135
        ///136
        ///137
        ///138
        ///139
        ///163
        ///170
        ///171
        ///159
        ///161
        ///162
        ///156
        ///155
        ///151
        ///168
        ///172
        ///166
        ///159
        ///180
        ///187
        ///172
        ///161
        ///162
        ///161
        ///183
        ///182
        ///185
        ///175
        ///173
        ///174
        ///177
        ///192
        ///191
        ///190
        ///219
        ///225
        ///226
        ///216
        ///226
        ///230
        ///234
        ///236
        ///244
        ///235
        ///245
        ///266
        ///299
        ///300
        ///281
        ///291
        ///309
        ///303
        ///333
        ///332
        ///309
        ///312
        ///313
        ///314
        ///315
        ///339
        ///351
        ///353
        ///352
        ///338
        ///343
        ///337
        ///346
        ///338
        ///335
        ///332
        ///329
        ///345
        ///347
        ///332
        ///339
        ///354
        ///373
        ///376
        ///397
        ///400
        ///401
        ///433
        ///434
        ///440
        ///434
        ///438
        ///443
        ///448
        ///452
        ///456
        ///450
        ///459
        ///463
        ///464
        ///488
        ///492
        ///488
        ///506
        ///507
        ///516
        ///523
        ///524
        ///522
        ///546
        ///551
        ///553
        ///554
        ///553
        ///562
        ///559
        ///567
        ///569
        ///556
        ///557
        ///577
        ///581
        ///582
        ///591
        ///593
        ///594
        ///595
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string input {
            get {
                return ResourceManager.GetString("input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 2
        ///down 4
        ///down 1
        ///down 4
        ///forward 3
        ///down 6
        ///down 5
        ///forward 3
        ///forward 8
        ///down 2
        ///down 3
        ///up 8
        ///down 5
        ///up 7
        ///down 7
        ///forward 5
        ///up 2
        ///down 6
        ///forward 7
        ///forward 1
        ///forward 2
        ///forward 7
        ///up 7
        ///forward 6
        ///down 3
        ///down 1
        ///up 9
        ///down 2
        ///up 1
        ///down 1
        ///up 6
        ///forward 6
        ///down 7
        ///forward 6
        ///up 1
        ///down 6
        ///forward 2
        ///up 7
        ///forward 4
        ///forward 8
        ///forward 7
        ///down 7
        ///forward 8
        ///down 1
        ///down 6
        ///down 7
        ///forward 4
        ///down 3
        ///up 7
        ///down 5
        ///down 9
        ///up 8
        ///up 4
        ///down 2
        ///down 3
        ///up 7
        ///forward 6
        ///forward 6
        ///forward 8
        ///forward 2
        ///up 5
        ///down 8
        ///down 3
        ///down 3
        ///down 4
        ///down 9
        ///down 6
        ///up 6
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inputDay2 {
            get {
                return ResourceManager.GetString("inputDay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101011111001
        ///100100110111
        ///101010101011
        ///010100010000
        ///001101101101
        ///110001101010
        ///001001011001
        ///101111101111
        ///110001001000
        ///111111000000
        ///111100110001
        ///101100010100
        ///000010000011
        ///000110000011
        ///101010100101
        ///000111001010
        ///100101101110
        ///111111010101
        ///110010001100
        ///000011001101
        ///001001111110
        ///100101001100
        ///000011100100
        ///000100110011
        ///000101101000
        ///101010011011
        ///101011110000
        ///010010110011
        ///110110101110
        ///001110000110
        ///001110111101
        ///110111100101
        ///000010101010
        ///101010101010
        ///011011001101
        ///110110000111
        ///011010011000
        ///000111000101
        ///100000101011
        ///01001 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inputDay3 {
            get {
                return ResourceManager.GetString("inputDay3", resourceCulture);
            }
        }
    }
}
